/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as TodosRouteRouteImport } from './routes/todos/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosIndexRouteImport } from './routes/todos/index'
import { Route as TodosCreateRouteImport } from './routes/todos/create'
import { Route as ApiTestRouteImport } from './routes/api/test'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as TodosTodoIdRouteRouteImport } from './routes/todos/$todoId/route'
import { Route as appSystemRouteRouteImport } from './routes/(app)/system/route'
import { Route as appDashboardRouteRouteImport } from './routes/(app)/dashboard/route'
import { Route as TodosTodoIdIndexRouteImport } from './routes/todos/$todoId/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register.index'
import { Route as appSystemIndexRouteImport } from './routes/(app)/system/index'
import { Route as appProfileIndexRouteImport } from './routes/(app)/profile/index'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as TodosTodoIdUpdateRouteImport } from './routes/todos/$todoId/update'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appSystemUsersRouteRouteImport } from './routes/(app)/system/users/route'
import { Route as appSystemRolesRouteRouteImport } from './routes/(app)/system/roles/route'
import { Route as appSystemUsersIndexRouteImport } from './routes/(app)/system/users/index'
import { Route as appSystemRolesIndexRouteImport } from './routes/(app)/system/roles/index'
import { Route as appSystemUsersCreateRouteImport } from './routes/(app)/system/users/create'
import { Route as appSystemRolesCreateRouteImport } from './routes/(app)/system/roles/create'
import { Route as appSystemUsersUserIdRouteRouteImport } from './routes/(app)/system/users/$userId/route'
import { Route as appSystemRolesRoleIdRouteRouteImport } from './routes/(app)/system/roles/$roleId/route'
import { Route as appSystemUsersUserIdIndexRouteImport } from './routes/(app)/system/users/$userId/index'
import { Route as appSystemUsersUserIdUpdateRouteImport } from './routes/(app)/system/users/$userId/update'
import { Route as appSystemRolesRoleIdUpdateRouteImport } from './routes/(app)/system/roles/$roleId/update'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRouteRoute = TodosRouteRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TodosRouteRoute,
} as any)
const TodosCreateRoute = TodosCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TodosRouteRoute,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const TodosTodoIdRouteRoute = TodosTodoIdRouteRouteImport.update({
  id: '/$todoId',
  path: '/$todoId',
  getParentRoute: () => TodosRouteRoute,
} as any)
const appSystemRouteRoute = appSystemRouteRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRouteRoute = appDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const TodosTodoIdIndexRoute = TodosTodoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TodosTodoIdRouteRoute,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const appSystemIndexRoute = appSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appSystemRouteRoute,
} as any)
const appProfileIndexRoute = appProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const TodosTodoIdUpdateRoute = TodosTodoIdUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => TodosTodoIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appSystemUsersRouteRoute = appSystemUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => appSystemRouteRoute,
} as any)
const appSystemRolesRouteRoute = appSystemRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => appSystemRouteRoute,
} as any)
const appSystemUsersIndexRoute = appSystemUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appSystemUsersRouteRoute,
} as any)
const appSystemRolesIndexRoute = appSystemRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appSystemRolesRouteRoute,
} as any)
const appSystemUsersCreateRoute = appSystemUsersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appSystemUsersRouteRoute,
} as any)
const appSystemRolesCreateRoute = appSystemRolesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appSystemRolesRouteRoute,
} as any)
const appSystemUsersUserIdRouteRoute =
  appSystemUsersUserIdRouteRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => appSystemUsersRouteRoute,
  } as any)
const appSystemRolesRoleIdRouteRoute =
  appSystemRolesRoleIdRouteRouteImport.update({
    id: '/$roleId',
    path: '/$roleId',
    getParentRoute: () => appSystemRolesRouteRoute,
  } as any)
const appSystemUsersUserIdIndexRoute =
  appSystemUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appSystemUsersUserIdRouteRoute,
  } as any)
const appSystemUsersUserIdUpdateRoute =
  appSystemUsersUserIdUpdateRouteImport.update({
    id: '/update',
    path: '/update',
    getParentRoute: () => appSystemUsersUserIdRouteRoute,
  } as any)
const appSystemRolesRoleIdUpdateRoute =
  appSystemRolesRoleIdUpdateRouteImport.update({
    id: '/update',
    path: '/update',
    getParentRoute: () => appSystemRolesRoleIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos': typeof TodosRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/dashboard': typeof appDashboardRouteRouteWithChildren
  '/system': typeof appSystemRouteRouteWithChildren
  '/todos/$todoId': typeof TodosTodoIdRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/api/test': typeof ApiTestRoute
  '/todos/create': typeof TodosCreateRoute
  '/todos/': typeof TodosIndexRoute
  '/system/roles': typeof appSystemRolesRouteRouteWithChildren
  '/system/users': typeof appSystemUsersRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/todos/$todoId/update': typeof TodosTodoIdUpdateRoute
  '/dashboard/': typeof appDashboardIndexRoute
  '/profile/': typeof appProfileIndexRoute
  '/system/': typeof appSystemIndexRoute
  '/register/': typeof authRegisterIndexRoute
  '/todos/$todoId/': typeof TodosTodoIdIndexRoute
  '/system/roles/$roleId': typeof appSystemRolesRoleIdRouteRouteWithChildren
  '/system/users/$userId': typeof appSystemUsersUserIdRouteRouteWithChildren
  '/system/roles/create': typeof appSystemRolesCreateRoute
  '/system/users/create': typeof appSystemUsersCreateRoute
  '/system/roles/': typeof appSystemRolesIndexRoute
  '/system/users/': typeof appSystemUsersIndexRoute
  '/system/roles/$roleId/update': typeof appSystemRolesRoleIdUpdateRoute
  '/system/users/$userId/update': typeof appSystemUsersUserIdUpdateRoute
  '/system/users/$userId/': typeof appSystemUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/api/test': typeof ApiTestRoute
  '/todos/create': typeof TodosCreateRoute
  '/todos': typeof TodosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/todos/$todoId/update': typeof TodosTodoIdUpdateRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/profile': typeof appProfileIndexRoute
  '/system': typeof appSystemIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/todos/$todoId': typeof TodosTodoIdIndexRoute
  '/system/roles/$roleId': typeof appSystemRolesRoleIdRouteRouteWithChildren
  '/system/roles/create': typeof appSystemRolesCreateRoute
  '/system/users/create': typeof appSystemUsersCreateRoute
  '/system/roles': typeof appSystemRolesIndexRoute
  '/system/users': typeof appSystemUsersIndexRoute
  '/system/roles/$roleId/update': typeof appSystemRolesRoleIdUpdateRoute
  '/system/users/$userId/update': typeof appSystemUsersUserIdUpdateRoute
  '/system/users/$userId': typeof appSystemUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/todos': typeof TodosRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/(app)/dashboard': typeof appDashboardRouteRouteWithChildren
  '/(app)/system': typeof appSystemRouteRouteWithChildren
  '/todos/$todoId': typeof TodosTodoIdRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/api/test': typeof ApiTestRoute
  '/todos/create': typeof TodosCreateRoute
  '/todos/': typeof TodosIndexRoute
  '/(app)/system/roles': typeof appSystemRolesRouteRouteWithChildren
  '/(app)/system/users': typeof appSystemUsersRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/todos/$todoId/update': typeof TodosTodoIdUpdateRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/profile/': typeof appProfileIndexRoute
  '/(app)/system/': typeof appSystemIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/todos/$todoId/': typeof TodosTodoIdIndexRoute
  '/(app)/system/roles/$roleId': typeof appSystemRolesRoleIdRouteRouteWithChildren
  '/(app)/system/users/$userId': typeof appSystemUsersUserIdRouteRouteWithChildren
  '/(app)/system/roles/create': typeof appSystemRolesCreateRoute
  '/(app)/system/users/create': typeof appSystemUsersCreateRoute
  '/(app)/system/roles/': typeof appSystemRolesIndexRoute
  '/(app)/system/users/': typeof appSystemUsersIndexRoute
  '/(app)/system/roles/$roleId/update': typeof appSystemRolesRoleIdUpdateRoute
  '/(app)/system/users/$userId/update': typeof appSystemUsersUserIdUpdateRoute
  '/(app)/system/users/$userId/': typeof appSystemUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/todos'
    | '/error'
    | '/dashboard'
    | '/system'
    | '/todos/$todoId'
    | '/forgot-password'
    | '/login'
    | '/api/test'
    | '/todos/create'
    | '/todos/'
    | '/system/roles'
    | '/system/users'
    | '/api/auth/$'
    | '/todos/$todoId/update'
    | '/dashboard/'
    | '/profile/'
    | '/system/'
    | '/register/'
    | '/todos/$todoId/'
    | '/system/roles/$roleId'
    | '/system/users/$userId'
    | '/system/roles/create'
    | '/system/users/create'
    | '/system/roles/'
    | '/system/users/'
    | '/system/roles/$roleId/update'
    | '/system/users/$userId/update'
    | '/system/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/api/test'
    | '/todos/create'
    | '/todos'
    | '/api/auth/$'
    | '/todos/$todoId/update'
    | '/dashboard'
    | '/profile'
    | '/system'
    | '/register'
    | '/todos/$todoId'
    | '/system/roles/$roleId'
    | '/system/roles/create'
    | '/system/users/create'
    | '/system/roles'
    | '/system/users'
    | '/system/roles/$roleId/update'
    | '/system/users/$userId/update'
    | '/system/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/todos'
    | '/error'
    | '/(app)/dashboard'
    | '/(app)/system'
    | '/todos/$todoId'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/api/test'
    | '/todos/create'
    | '/todos/'
    | '/(app)/system/roles'
    | '/(app)/system/users'
    | '/api/auth/$'
    | '/todos/$todoId/update'
    | '/(app)/dashboard/'
    | '/(app)/profile/'
    | '/(app)/system/'
    | '/(auth)/register/'
    | '/todos/$todoId/'
    | '/(app)/system/roles/$roleId'
    | '/(app)/system/users/$userId'
    | '/(app)/system/roles/create'
    | '/(app)/system/users/create'
    | '/(app)/system/roles/'
    | '/(app)/system/users/'
    | '/(app)/system/roles/$roleId/update'
    | '/(app)/system/users/$userId/update'
    | '/(app)/system/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  TodosRouteRoute: typeof TodosRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  ApiTestRoute: typeof ApiTestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/': {
      id: '/todos/'
      path: '/'
      fullPath: '/todos/'
      preLoaderRoute: typeof TodosIndexRouteImport
      parentRoute: typeof TodosRouteRoute
    }
    '/todos/create': {
      id: '/todos/create'
      path: '/create'
      fullPath: '/todos/create'
      preLoaderRoute: typeof TodosCreateRouteImport
      parentRoute: typeof TodosRouteRoute
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/todos/$todoId': {
      id: '/todos/$todoId'
      path: '/$todoId'
      fullPath: '/todos/$todoId'
      preLoaderRoute: typeof TodosTodoIdRouteRouteImport
      parentRoute: typeof TodosRouteRoute
    }
    '/(app)/system': {
      id: '/(app)/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof appSystemRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/todos/$todoId/': {
      id: '/todos/$todoId/'
      path: '/'
      fullPath: '/todos/$todoId/'
      preLoaderRoute: typeof TodosTodoIdIndexRouteImport
      parentRoute: typeof TodosTodoIdRouteRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/system/': {
      id: '/(app)/system/'
      path: '/'
      fullPath: '/system/'
      preLoaderRoute: typeof appSystemIndexRouteImport
      parentRoute: typeof appSystemRouteRoute
    }
    '/(app)/profile/': {
      id: '/(app)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof appProfileIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/todos/$todoId/update': {
      id: '/todos/$todoId/update'
      path: '/update'
      fullPath: '/todos/$todoId/update'
      preLoaderRoute: typeof TodosTodoIdUpdateRouteImport
      parentRoute: typeof TodosTodoIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/system/users': {
      id: '/(app)/system/users'
      path: '/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof appSystemUsersRouteRouteImport
      parentRoute: typeof appSystemRouteRoute
    }
    '/(app)/system/roles': {
      id: '/(app)/system/roles'
      path: '/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof appSystemRolesRouteRouteImport
      parentRoute: typeof appSystemRouteRoute
    }
    '/(app)/system/users/': {
      id: '/(app)/system/users/'
      path: '/'
      fullPath: '/system/users/'
      preLoaderRoute: typeof appSystemUsersIndexRouteImport
      parentRoute: typeof appSystemUsersRouteRoute
    }
    '/(app)/system/roles/': {
      id: '/(app)/system/roles/'
      path: '/'
      fullPath: '/system/roles/'
      preLoaderRoute: typeof appSystemRolesIndexRouteImport
      parentRoute: typeof appSystemRolesRouteRoute
    }
    '/(app)/system/users/create': {
      id: '/(app)/system/users/create'
      path: '/create'
      fullPath: '/system/users/create'
      preLoaderRoute: typeof appSystemUsersCreateRouteImport
      parentRoute: typeof appSystemUsersRouteRoute
    }
    '/(app)/system/roles/create': {
      id: '/(app)/system/roles/create'
      path: '/create'
      fullPath: '/system/roles/create'
      preLoaderRoute: typeof appSystemRolesCreateRouteImport
      parentRoute: typeof appSystemRolesRouteRoute
    }
    '/(app)/system/users/$userId': {
      id: '/(app)/system/users/$userId'
      path: '/$userId'
      fullPath: '/system/users/$userId'
      preLoaderRoute: typeof appSystemUsersUserIdRouteRouteImport
      parentRoute: typeof appSystemUsersRouteRoute
    }
    '/(app)/system/roles/$roleId': {
      id: '/(app)/system/roles/$roleId'
      path: '/$roleId'
      fullPath: '/system/roles/$roleId'
      preLoaderRoute: typeof appSystemRolesRoleIdRouteRouteImport
      parentRoute: typeof appSystemRolesRouteRoute
    }
    '/(app)/system/users/$userId/': {
      id: '/(app)/system/users/$userId/'
      path: '/'
      fullPath: '/system/users/$userId/'
      preLoaderRoute: typeof appSystemUsersUserIdIndexRouteImport
      parentRoute: typeof appSystemUsersUserIdRouteRoute
    }
    '/(app)/system/users/$userId/update': {
      id: '/(app)/system/users/$userId/update'
      path: '/update'
      fullPath: '/system/users/$userId/update'
      preLoaderRoute: typeof appSystemUsersUserIdUpdateRouteImport
      parentRoute: typeof appSystemUsersUserIdRouteRoute
    }
    '/(app)/system/roles/$roleId/update': {
      id: '/(app)/system/roles/$roleId/update'
      path: '/update'
      fullPath: '/system/roles/$roleId/update'
      preLoaderRoute: typeof appSystemRolesRoleIdUpdateRouteImport
      parentRoute: typeof appSystemRolesRoleIdRouteRoute
    }
  }
}

interface appDashboardRouteRouteChildren {
  appDashboardIndexRoute: typeof appDashboardIndexRoute
}

const appDashboardRouteRouteChildren: appDashboardRouteRouteChildren = {
  appDashboardIndexRoute: appDashboardIndexRoute,
}

const appDashboardRouteRouteWithChildren =
  appDashboardRouteRoute._addFileChildren(appDashboardRouteRouteChildren)

interface appSystemRolesRoleIdRouteRouteChildren {
  appSystemRolesRoleIdUpdateRoute: typeof appSystemRolesRoleIdUpdateRoute
}

const appSystemRolesRoleIdRouteRouteChildren: appSystemRolesRoleIdRouteRouteChildren =
  {
    appSystemRolesRoleIdUpdateRoute: appSystemRolesRoleIdUpdateRoute,
  }

const appSystemRolesRoleIdRouteRouteWithChildren =
  appSystemRolesRoleIdRouteRoute._addFileChildren(
    appSystemRolesRoleIdRouteRouteChildren,
  )

interface appSystemRolesRouteRouteChildren {
  appSystemRolesRoleIdRouteRoute: typeof appSystemRolesRoleIdRouteRouteWithChildren
  appSystemRolesCreateRoute: typeof appSystemRolesCreateRoute
  appSystemRolesIndexRoute: typeof appSystemRolesIndexRoute
}

const appSystemRolesRouteRouteChildren: appSystemRolesRouteRouteChildren = {
  appSystemRolesRoleIdRouteRoute: appSystemRolesRoleIdRouteRouteWithChildren,
  appSystemRolesCreateRoute: appSystemRolesCreateRoute,
  appSystemRolesIndexRoute: appSystemRolesIndexRoute,
}

const appSystemRolesRouteRouteWithChildren =
  appSystemRolesRouteRoute._addFileChildren(appSystemRolesRouteRouteChildren)

interface appSystemUsersUserIdRouteRouteChildren {
  appSystemUsersUserIdUpdateRoute: typeof appSystemUsersUserIdUpdateRoute
  appSystemUsersUserIdIndexRoute: typeof appSystemUsersUserIdIndexRoute
}

const appSystemUsersUserIdRouteRouteChildren: appSystemUsersUserIdRouteRouteChildren =
  {
    appSystemUsersUserIdUpdateRoute: appSystemUsersUserIdUpdateRoute,
    appSystemUsersUserIdIndexRoute: appSystemUsersUserIdIndexRoute,
  }

const appSystemUsersUserIdRouteRouteWithChildren =
  appSystemUsersUserIdRouteRoute._addFileChildren(
    appSystemUsersUserIdRouteRouteChildren,
  )

interface appSystemUsersRouteRouteChildren {
  appSystemUsersUserIdRouteRoute: typeof appSystemUsersUserIdRouteRouteWithChildren
  appSystemUsersCreateRoute: typeof appSystemUsersCreateRoute
  appSystemUsersIndexRoute: typeof appSystemUsersIndexRoute
}

const appSystemUsersRouteRouteChildren: appSystemUsersRouteRouteChildren = {
  appSystemUsersUserIdRouteRoute: appSystemUsersUserIdRouteRouteWithChildren,
  appSystemUsersCreateRoute: appSystemUsersCreateRoute,
  appSystemUsersIndexRoute: appSystemUsersIndexRoute,
}

const appSystemUsersRouteRouteWithChildren =
  appSystemUsersRouteRoute._addFileChildren(appSystemUsersRouteRouteChildren)

interface appSystemRouteRouteChildren {
  appSystemRolesRouteRoute: typeof appSystemRolesRouteRouteWithChildren
  appSystemUsersRouteRoute: typeof appSystemUsersRouteRouteWithChildren
  appSystemIndexRoute: typeof appSystemIndexRoute
}

const appSystemRouteRouteChildren: appSystemRouteRouteChildren = {
  appSystemRolesRouteRoute: appSystemRolesRouteRouteWithChildren,
  appSystemUsersRouteRoute: appSystemUsersRouteRouteWithChildren,
  appSystemIndexRoute: appSystemIndexRoute,
}

const appSystemRouteRouteWithChildren = appSystemRouteRoute._addFileChildren(
  appSystemRouteRouteChildren,
)

interface appRouteRouteChildren {
  appDashboardRouteRoute: typeof appDashboardRouteRouteWithChildren
  appSystemRouteRoute: typeof appSystemRouteRouteWithChildren
  appProfileIndexRoute: typeof appProfileIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardRouteRoute: appDashboardRouteRouteWithChildren,
  appSystemRouteRoute: appSystemRouteRouteWithChildren,
  appProfileIndexRoute: appProfileIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface TodosTodoIdRouteRouteChildren {
  TodosTodoIdUpdateRoute: typeof TodosTodoIdUpdateRoute
  TodosTodoIdIndexRoute: typeof TodosTodoIdIndexRoute
}

const TodosTodoIdRouteRouteChildren: TodosTodoIdRouteRouteChildren = {
  TodosTodoIdUpdateRoute: TodosTodoIdUpdateRoute,
  TodosTodoIdIndexRoute: TodosTodoIdIndexRoute,
}

const TodosTodoIdRouteRouteWithChildren =
  TodosTodoIdRouteRoute._addFileChildren(TodosTodoIdRouteRouteChildren)

interface TodosRouteRouteChildren {
  TodosTodoIdRouteRoute: typeof TodosTodoIdRouteRouteWithChildren
  TodosCreateRoute: typeof TodosCreateRoute
  TodosIndexRoute: typeof TodosIndexRoute
}

const TodosRouteRouteChildren: TodosRouteRouteChildren = {
  TodosTodoIdRouteRoute: TodosTodoIdRouteRouteWithChildren,
  TodosCreateRoute: TodosCreateRoute,
  TodosIndexRoute: TodosIndexRoute,
}

const TodosRouteRouteWithChildren = TodosRouteRoute._addFileChildren(
  TodosRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  TodosRouteRoute: TodosRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  ApiTestRoute: ApiTestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
